---
- name: Fast SSH Connectivity & Availability Check
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Test raw SSH execution
      ansible.builtin.raw: echo PONG
      register: ping_test
      changed_when: false
      timeout: 10
